#Must contain '{amount}', '{owner}' is optional#
moneyVoucher:
  title: '&e&lBank Note &7(Click)'
  lore:
    - '&eValue:&f ${amount}'
    - '&eSigner:&f {owner}'

expVoucher:
  title: '&a&lExperience Bottle &7(Click)'
  lore:
    - '&aValue:&f {amount} EXP'
    - '&aEnchanter:&f {owner}'

mcmmoVoucher:
  title: '&c&lMcmmo Credits &7(Click)'
  lore:
    - '&cValue:&f {amount} Credits'
    - '&cTrainer:&f {owner}'

#To use multiple lines, seperate them by a '%'#
commandMessages:
  NOT_ENOUGH_EXP: '&cYou do not have enough exp.'
  EXP_WITHDRAW: '&c&l-{amount} EXP'
  EXP_DEPOSIT: '&a&l+{amount} EXP'
  NOT_ENOUGH_MONEY: '&cYou do not have enough money.'
  MONEY_WITHDRAW: '&c&l-${amount}%&aYou have signed a bank note for ${amount}.'
  MONEY_DEPOSIT: '&a&l+${amount}'
  NOT_ENOUGH_MCMMO: '&cYou do not have enough mcmmo credits.'
  MCMMO_WITHDRAW: '&c&l-{amount} Credits'
  MCMMO_DEPOSIT: '&a&l+{amount} Credits'
  EXP_USAGE: '&a/xpbottle <amount>%&7Withdraws exp from your exp bar into a bottle.'
  MONEY_USAGE: '&e/withdraw <amount>%&7Withdraws money from your balance into a bank note.'
  MCMMO_USAGE: '&c/withdrawmcmmo <amount>%&7Withdraws mcmmo credits from your balance.'
  NO_PERMISSION: '&cYou don''t have permission to do this'
  EXP_MAX: '&cYou cannot withdraw more than 2147483647 exp'
  EXP_MIN: '&cYou cannot withdraw less than 1 exp'
  MONEY_MAX: '&cYou cannot withdraw more than $2147483647'
  MONEY_MIN: '&cYou cannot withdraw less than $1'
  MCMMO_MAX: '&cYou cannot withdraw more than 2147483647 mcmmo credits'
  MCMMO_MIN: '&cYou cannot withdraw less than 1 mcmmo credit'
  EXP_BAL: '&aExperience: &f{amount}'

#Needs to be 1 word, no spaces allowed!#
commands:
  MONEY_WITHDRAW_COMMAND: '/withdraw'
  EXP_WITHDRAW_COMMAND: '/withdrawxp'
  MCMMO_WITHDRAW_COMMAND: '/withdrawmcmmo'

#Use official item names, having trouble? look here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#
#After you change the item, all already existing voucher will get invalid.#
#The names are not case sensitive#
items:
  MONEY_ITEM: 'paper'
  EXP_ITEM: 'exp_bottle'
  MCMMO_ITEM: 'magma_cream'

#Use official sound names, having trouble? look here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html#
#The names are not case sensitive#
sounds:
  MONEY_SOUND: 'wood_click'
  EXP_SOUND: 'wood_click'
  MCMMO_SOUND: 'wood_click'

#Minimum and maximum values you can withdraw.#
#This can never be less than 1 ore more than 2147483647#
minMaxValues:
  MIN_EXP: 1
  MAX_EXP: 2147483647
  MIN_MONEY: 1
  MAX_MONEY: 2147483647
  MIN_MCMMO: 1
  MAX_MCMMO: 2147483647

misc:
  #The name of the owner of the voucher you get by using the /givevoucher command#
  defaultOwnerName: 'Vyzon Network'
